Zachary Loschinskey

December 2024

Formally learning Julia syntax over the break

Following this course

https://juliaacademy.com/courses/375479/

In [17]:
# Printing
println("This is how to print")

# Assigning Variables -> Julia is dynamically typed
x = 42
println(typeof(x))

my_pi = 3.14159
println(typeof(my_pi))

# Note that any unicode character can be used as a variable name
🍕 = "Hello World!"
println(typeof(🍕))

#=
For multi-line comments
you can do something like this
=#

# Basic math is the same as in python for the most part except:
power = 10^2

# The convert function can be used to convert data types
convert(Float64, power)

This is how to print
Int64
Float64
String


100.0

In [27]:
# strings can be defined in two ways -> you can use triple quotes if you need to use quotes inside your string too
mystr = "This is my string"
mystr2 = """This is also "my" string"""
println(mystr2)

# Note you can't use single quotes to define strings
# Printing variables inside strings
myPizza = "pepporoni"
numPizzas = 5
println("I have $numPizzas $myPizza pizzas")

# Strings can be concatenated using the string function
mystr = string("Hello", " World")
println(mystr)

# You can also use the star operator
mystr = "Hello"*" World"
println(mystr)

This is also "my" string
I have 5 pepporoni pizzas
Hello World
Hello World


In [ ]:
# Julia Dictionaries
myphonebook = Dict("Allie" => "312-415-1523", "Zach" => "101-182-4120")

# Add another entry
myphonebook["Jake"] = "201-837-3838"

println(myphonebook)

# To get a single element
println(myphonebook["Zach"])

# pop! function will delete entry and return the value at that key
pop!(myphonebook, "Zach")
println(myphonebook)

Dict("Jake" => "201-837-3838", "Andrea" => "312-415-1523", "Zach" => "101-182-4120")
101-182-4120
Dict("Jake" => "201-837-3838", "Andrea" => "312-415-1523")


In [ ]:
# Julia Tuples -> sequential structures in Julia are base 1
myfavanimals = ("Cats", "Dogs", "Hamsters")
println(myfavanimals[1])

# Note that tuples are immutable -> they can't be changed once defined

Cats


In [49]:
# Julia Arrays -> sequential, mutable
myfriends = ["Bob", "Linda", "Tina", "Louise", "Gene"]
fibonacci = [1, 1, 2, 3, 5, 8, 13]
mix = [1, 2, 3, "hi"]

println(typeof(myfriends))
println(typeof(fibonacci))
println(typeof(mix))

# To index we use base 1 indexing
println(myfriends[2])

# You can add elements using the push!(array, element) function -> adds to end of array
push!(fibonacci, 21)
println(fibonacci)

# You can remove elements using the pop!(array) fucntion -> takes off last element
pop!(fibonacci)
println(fibonacci)

# You can also create multidimensional Arrays -> they are column major
rand(4,3,2)



Vector{String}
Vector{Int64}
Vector{Any}
Linda
[1, 1, 2, 3, 5, 8, 13, 21]
[1, 1, 2, 3, 5, 8, 13]


4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.754015  0.878893    0.745331
 0.580797  0.00880785  0.110161
 0.560903  0.672003    0.632901
 0.980287  0.396603    0.873341

[:, :, 2] =
 0.0913707  0.969497  0.583143
 0.252497   0.104377  0.945368
 0.588886   0.160317  0.43937
 0.08917    0.384865  0.729455

In [54]:
# While loops in Julia
n = 0
while n<5
    println(n)
    n+=1
end


0
1
2
3
4


In [61]:
# For loops in Julia
for n in 0:4
    println(n)
end

println()

mylist = ["Jimmy Jr.", "Jimmy Pest", "Hugo", "Ron"]
for element in mylist
    println(element)
end

# Note: you can replace the "in" keyword with "=" or "∈" (\in)

0
1
2
3
4

Jimmy Jr.
Jimmy Pest
Hugo
Ron


In [64]:
# Typical nested for loop
m, n = 5, 5
A = zeros(m, n)

for i in 1:m
    for j in 1:n
        A[i,j] = i+j
    end
end

A

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [68]:
# Double for loop
B = zeros(m, n)
for i in 1:m, j in 1:n
    B[i,j] = i+j
end
B

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [70]:
# Array comprehension
C = [i+j for i in 1:m, j in 1:n]
C

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10